apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: log-service
  namespace: {{ .Release.Namespace }}
stringData:
  LOG_SERVICE_S3_ACCESS_KEY_ID: {{ .Values.global.s3.accessKeyId  }}
  LOG_SERVICE_S3_SECRET_ACCESS_KEY: {{ .Values.global.s3.secretAccessKey }}