apiVersion: v1
kind: Service
metadata:
  name: log-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "log-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: log-service
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    {{- include "log-service.selectorLabels" . | nindent 4 }}
